### ISSUE TITLE
ValueError: unsupported format character '(' (0x28) at index 2

### ISSUE THREAD

**Issue by buaaluwentao** [M-Gregoire/Cuckoo2Mist#1]
When I run the script in the shell using the cmd `python3 cuckoo2mist.py  -i="/home/luwentso/.cuckoo/storage/analyses/6/reports/"`，I can get the error information above everywhere the `log.warning` occurs like 
```
File "/home/luwentso/cuckoo2mist/cc3/Cuckoo2Mist-master/Cuckoo2Mist/class_mist.py", line 309, in convert log.warning(u"Category <%s> does not exists in the XML" % key )
```

I know it is the encoding, but I am new to python, any help,
Thanks,^__^.

**Comment by M-Gregoire** [comment]
Hi,
I'm sorry for the late answer. Can you provide : 

- The exact version of Python you are using

When creating an issue, please use the `code tags` to help the readability (see your edited comment).

**Comment by krunalpuri** [comment]
Hi,

I got the same error when I tried to run it with python version 3.6.7.
