### ISSUE TITLE
Logging Basic Configuration (Fixes ValueError: unsupported format character '(' (0x28) at index 2)

### ISSUE THREAD

**Issue by krunalpuri** [M-Gregoire/Cuckoo2Mist#2]
https://github.com/M-Gregoire/Cuckoo2Mist/blob/5da842a16d52415b3181e41371f20257db774d34/Cuckoo2Mist/cuckoo2mist.py#L112

@M-Gregoire 
Follow up to the issue #1 
Error is caused by logging api.
Please change this line to:
log.basicConfig(format="%(levelname)s: %(message)s",level=log.ERROR)
Thank you.

**Comment by M-Gregoire** [comment]
I'm sorry for the time I took to get back to you, I don't really have time to maintain this project.

Thank you for your contribution.
